converter:
    slug: "unity-550f3"
    class: UnityZippedFbxConverter
    config:
        unity_executable: b
        unity_converter_project_path: d
connection:
    host: localhost
    port: 8000
    path: assets/pipeline
